image:
  repository: hub.yourdomain.com/example/frontend
  tag: 11a14195e5c663f3baf910e0d19a214e73f3dee3
  pullPolicy: IfNotPresent
backend:
  debug: "true"
  active: localhost
  datasource:
    url: "jdbc:mysql://***:3306/dbname?useUnicode=true&characterEncoding=utf8mb4&useSSL=false"
    host: hostname
    database: dbname
    username: username
    password: "***"
